[package]
name = "sendgrid_thin"
version = "0.1.7"
edition = "2021"
authors = ["OLoKo64 <reinaldorozatoj.11cg1@aleeas.com>"]
description = "A small unofficial library to send emails using Sendgrid."
categories = ["api-bindings"]
homepage = "https://sendgrid.com"
repository = "https://github.com/OLoKo64/sendgrid_thin"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
ureq = "2.5.0"
